;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        beginning-of-visual-line
        comment-dwim
        delete-horizontal-space
        electric-newline-and-maybe-indent
        end-of-visual-line
        eval-and-replace
        forward-sexp
        hippie-expand-no-case-fold
        kill-and-retry-line
        kill-region-or-backward-word
        matlab-backward-sexp
        matlab-electric-comment
        matlab-forward-sexp
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-self-insert-command
        save-region-or-current-line
        transpose-params
        ))

(setq mc/cmds-to-run-once
      '(
        ))
