
;; Asynchronous execution of org-mode code blocks
(use-package ob-async)

;; Display inline images generated by code execution.
(add-hook 'org-babel-after-execute-hook
          'org-display-inline-images)

;; Execute code blocks in these languages.
                                        ;(use-package ob-ipython :defer t)
;; (add-to-list 'load-path
;;              "~/.emacs.d/other-packages/ob-julia/")
;; (setq inferior-julia-program-name
;;       (expand-file-name "~/bin/julia"))

(org-babel-do-load-languages
 'org-babel-load-languages
 '( (emacs-lisp . t)
    (shell . t)
    ;;(julia . t)
    ;;(python . t)
    (ipython . t)
    (R . t)
    ;;(clojure . t)
    ;;(js . t)
    ;;(matlab . t)
    ))
